# ===============================================
# Skaffold Configuration
# ===============================================

apiVersion: skaffold/v2alpha3
kind: Config

# ------------------------------------------------------------------------------

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth/*
      - ./infra/k8s/client/*
      - ./infra/k8s/expirations/*
      - ./infra/k8s/nats/*
      - ./infra/k8s/orders/*
      - ./infra/k8s/payments/*
      - ./infra/k8s/tickets/*
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/notifications/*

# ------------------------------------------------------------------------------

build:
  # Local is used to build the images locally
  local:
    push: false

  # Artifacts is used to define the artifacts to be built
  artifacts:
    # Auth Service
    - image: h3nrzi/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "auth/src/**/*.ts"
            dest: .
    # Tickets Service
    - image: h3nrzi/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "tickets/src/**/*.ts"
            dest: .
    # Orders Service
    - image: h3nrzi/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "orders/src/**/*.ts"
            dest: .
    # Expirations Service
    - image: h3nrzi/expirations
      context: expirations
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "expirations/src/**/*.ts"
            dest: .
    # Payments Service
    - image: h3nrzi/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "payments/src/**/*.ts"
            dest: .
    # Notifications Service
    - image: h3nrzi/notifications
      context: notifications
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "notifications/src/**/*.ts"
            dest: .