apiVersion: v1
kind: Service

# ------------------------------------------------------------------------------

metadata:
  name: tickets-srv

# ------------------------------------------------------------------------------

spec:
  # Selector is used to select the pods to be managed by the service
  selector:
    app: tickets

  # Ports is used to define the ports to be exposed by the service
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000