apiVersion: apps/v1
kind: Deployment

# ------------------------------------------------------------------------------

metadata:
  name: tickets-depl

# ------------------------------------------------------------------------------

spec:
  # Replicas is used to define the number of replicas of the deployment
  replicas: 1

  # Selector is used to select the pods to be managed by the deployment
  selector:
    matchLabels:
      app: tickets

  # Template is used to define the pod template
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: h3nrzi/tickets:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

