# ===============================================
# Deployment Definition
# ===============================================

apiVersion: apps/v1
kind: Deployment

# ------------------------------------------------------------------------------

metadata:
  name: nats-depl

# ------------------------------------------------------------------------------

spec:
  # Replicas is used to define the number of replicas of the deployment
  replicas: 1

  # Selector is used to select the pods to be managed by the deployment
  selector:
    matchLabels:
      app: nats

  # Template is used to define the pod template
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args: [
              "-p", # port
              "4222",
              "-m", # memory
              "8222",
              "-hbi", # heartbeat interval
              "5s",
              "-hbt", # heartbeat timeout
              "5s",
              "-hbf", # heartbeat frequency
              "2",
              "-SD", # store dir
              "-cid", # cluster id
              "ticketing",
            ]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---

# ===============================================
# Service Definition
# ===============================================

apiVersion: v1
kind: Service

# ------------------------------------------------------------------------------

metadata:
  name: nats-srv

# ------------------------------------------------------------------------------

spec:
  # Selector is used to select the pods to be managed by the service
  selector:
    app: nats

  # Ports is used to define the ports to be exposed by the service
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
