import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
