# ===============================================
# Deployment Definition
# ===============================================

apiVersion: apps/v1
kind: Deployment

# ------------------------------------------------------------------------------

metadata:
  name: orders-depl

# ------------------------------------------------------------------------------

spec:
  # Replicas is used to define the number of replicas of the deployment
  replicas: 1

  # Selector is used to select the pods to be managed by the deployment
  selector:
    matchLabels:
      app: orders

  # Template is used to define the pod template
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: h3nrzi/orders:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: MONGO_URI
              value: mongodb://orders-mongo-srv:27017/orders
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
# ------------------------------------------------------------------------------

# ===============================================
# Service Definition
# ===============================================

apiVersion: v1
kind: Service

# ------------------------------------------------------------------------------

metadata:
  name: orders-srv

# ------------------------------------------------------------------------------

spec:
  # Selector is used to select the pods to be managed by the service
  selector:
    app: orders

  # Ports is used to define the ports to be exposed by the service
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
