apiVersion: apps/v1
kind: Deployment

# ------------------------------------------------------------------------------

metadata:
  name: payments-mongo-depl

# ------------------------------------------------------------------------------

spec:
  # Replicas is used to define the number of replicas of the deployment
  replicas: 1

  # Selector is used to select the pods to be managed by the deployment
  selector:
    matchLabels:
      app: payments-mongo

  # Template is used to define the pod template
  template:
    metadata:
      labels:
        app: payments-mongo
    spec:
      containers:
        - name: payments-mongo
          image: mongo:4.4.6
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
