apiVersion: v1
kind: Service

# ------------------------------------------------------------------------------

metadata:
  name: expirations-redis-srv

# ------------------------------------------------------------------------------

spec:
  # Selector is used to select the pods to be managed by the service
  selector:
    app: expirations-redis

  # Ports is used to define the ports to be exposed by the service
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379