# ===============================================
# Deployment Definition
# ===============================================

apiVersion: apps/v1
kind: Deployment

# ------------------------------------------------------------------------------

metadata:
  name: expiration-redis-depl

# ------------------------------------------------------------------------------

spec:
  # Replicas is used to define the number of replicas of the deployment
  replicas: 1

  # Selector is used to select the pods to be managed by the deployment
  selector:
    matchLabels:
      app: expiration-redis

  # Template is used to define the pod template
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
        - name: expiration-redis
          image: redis:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---

# ------------------------------------------------------------------------------

# ===============================================
# Service Definition
# ===============================================

apiVersion: v1
kind: Service

# ------------------------------------------------------------------------------

metadata:
  name: expiration-redis-srv

# ------------------------------------------------------------------------------

spec:
  # Selector is used to select the pods to be managed by the service
  selector:
    app: expiration-redis

  # Ports is used to define the ports to be exposed by the service
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
