apiVersion: v1
kind: Service

metadata:
  name: notifications-srv

spec:
  selector:
    app: notifications
  ports:
    - name: notifications
      protocol: TCP
      port: 3000
      targetPort: 3000
